
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib import colors
from reportlab.graphics.shapes import Drawing
from reportlab.graphics.charts.barcharts import VerticalBarChart
from io import BytesIO

def build_pdf_report(audit, category_scores, strengths, weaknesses, priority_fixes):
    buf = BytesIO()
    c = canvas.Canvas(buf, pagesize=A4)

    # Page 1: Cover
    c.setFont("Helvetica-Bold", 16)
    c.drawString(50, 800, "FF Tech AI Website Audit Report")
    c.drawString(50, 770, f"Score: {audit.score}% | Grade: {audit.grade}")
    c.drawString(50, 750, f"Audited URL: {audit.url}")
    c.showPage()

    # Page 2: Category Breakdown Chart
    d = Drawing(400, 200)
    bc = VerticalBarChart()
    bc.x = 30; bc.y = 30
    bc.height = 140; bc.width = 340
    bc.data = [[category_scores.get(k, 0) for k in ['security','performance','seo','mobile','content']]]
    bc.categoryAxis.categoryNames = ['Security','Performance','SEO','Mobile','Content']
    bc.valueAxis.valueMin = 0; bc.valueAxis.valueMax = 100
    bc.bars[0].fillColor = colors.HexColor('#00ADB5')
    d.add(bc)
    d.drawOn(c, 50, 500)
    c.showPage()

    # Page 3: Strengths & Weaknesses
    c.drawString(50, 800, "Strengths:")
    y = 780
    for s in strengths: c.drawString(60, y, f"• {s}"); y -= 15
    c.drawString(300, 800, "Weaknesses:")
    y = 780
    for w in weaknesses: c.drawString(310, y, f"• {w}"); y -= 15
    c.showPage()

    # Page 4: Priority Fixes
    c.drawString(50, 800, "Priority Fixes:")
    y = 780
    for p in priority_fixes: c.drawString(60, y, f"• {p}"); y -= 15
    c.showPage()

    # Page 5: Certification
    c.drawString(50, 800, "Certified Audit Report")
    c.drawString(50, 780, "Generated by FF Tech AI Website Audit SaaS")
    c.showPage()

    c.save()
    return buf.getvalue()
