# fftech_audit/ui_and_pdf.py
from io import BytesIO
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.pdfgen import canvas

# Build a 5-page PDF with premium styling + logo

def build_pdf_report(audit, metrics) -> bytes:
    buf = BytesIO()
    c = canvas.Canvas(buf, pagesize=A4)
    W, H = A4

    def header(title, subtitle=None):
        # Try to draw logo; fallback to bar
        try:
            c.drawImage("static/logo.png", 20, H-36, width=80, height=24, preserveAspectRatio=True, mask="auto")
        except Exception:
            pass
        c.setFillColorRGB(0.11,0.16,0.32)
        c.rect(0, H-40, W, 40, fill=1, stroke=0)
        c.setFillColor(colors.white)
        c.setFont("Helvetica-Bold", 16)
        c.drawString(110, H-28, title)
        if subtitle:
            c.setFont("Helvetica", 11)
            c.drawString(110, H-45, subtitle)

    # Page 1: Title & summary
    header("FF Tech • Website Audit Report", subtitle="Executive summary")
    c.setFillColor(colors.black)
    c.setFont("Helvetica-Bold", 14)
    url = getattr(audit, 'url', 'URL')
    c.drawString(20, H-80, f"Audited URL: {url}")
    summary = metrics[3]["value"]
    text = c.beginText(20, H-110)
    text.setFont("Helvetica", 11)
    for line in summary.split('. '):
        text.textLine(line.strip())
    c.drawText(text)
    c.setFont("Helvetica", 10)
    c.drawString(20, 30, "© FF Tech • Generated by FFTech Audit Engine")
    c.showPage()

    # Page 2: Score & Grade + Severity
    header("Score, Grade, and Severity")
    score = metrics[1]["value"]; grade = metrics[2]["value"]
    sev = metrics[7]["value"]
    c.setFont("Helvetica-Bold", 24);
    c.setFillColor(colors.green)
    c.drawString(20, H-100, f"Score: {score}%")
    c.setFillColor(colors.darkgreen)
    c.drawString(20, H-130, f"Grade: {grade}")
    c.setFillColor(colors.red); c.rect(20, H-200, 150, 30, fill=1)
    c.setFillColor(colors.white); c.setFont("Helvetica-Bold", 12); c.drawString(30, H-190, f"Errors: {sev['errors']}")
    c.setFillColor(colors.orange); c.rect(190, H-200, 150, 30, fill=1)
    c.setFillColor(colors.white); c.drawString(200, H-190, f"Warnings: {sev['warnings']}")
    c.setFillColor(colors.gold); c.rect(360, H-200, 150, 30, fill=1)
    c.setFillColor(colors.black); c.drawString(370, H-190, f"Notices: {sev['notices']}")
    c.showPage()

    # Page 3: Category chart (simple bars)
    header("Category Breakdown")
    cat = metrics[8]["value"]
    x0, y0 = 60, H-150
    bar_w, gap = 40, 30
    colors_map = [colors.blue, colors.purple, colors.orange, colors.red, colors.green]
    for i, name in enumerate(["Crawlability","On-Page SEO","Performance","Security","Mobile"]):
        val = int(cat.get(name, 0))
        c.setFillColor(colors_map[i])
        c.rect(x0 + i*(bar_w+gap), y0- val*2, bar_w, val*2, fill=1, stroke=0)
        c.setFillColor(colors.black)
        c.setFont("Helvetica", 10)
        c.drawString(x0 + i*(bar_w+gap), y0 + 10, name)
        c.drawString(x0 + i*(bar_w+gap), y0 - val*2 - 12, f"{val}%")
    c.showPage()

    # Page 4: Strengths & Weaknesses
    header("Strengths and Weaknesses")
    strengths = metrics[4]["value"]
    weaknesses = metrics[5]["value"]
    c.setFont("Helvetica-Bold", 12)
    c.drawString(20, H-80, "Strengths:")
    c.setFont("Helvetica", 11)
    y = H-100
    for s in strengths[:10]:
        c.drawString(28, y, f"• {s}"); y -= 18
    c.setFont("Helvetica-Bold", 12)
    c.drawString(300, H-80, "Weaknesses:")
    c.setFont("Helvetica", 11)
    y = H-100
    for w in weaknesses[:10]:
        c.drawString(308, y, f"• {w}"); y -= 18
    c.showPage()

    # Page 5: Priority fixes + key metrics table (top 10)
    header("Priority Fixes & Key Metrics")
    fixes = metrics[6]["value"]
    c.setFont("Helvetica-Bold", 12)
    c.drawString(20, H-80, "Priority Fixes:")
    c.setFont("Helvetica", 11)
    y = H-100
    for pf in fixes[:10]:
        c.drawString(28, y, f"• {pf}"); y -= 18
    c.setFont("Helvetica-Bold", 12)
    c.drawString(20, H-260, "Key Numeric Metrics:")
    c.setFont("Helvetica", 11)
    y = H-280
    count = 0
    for pid in range(1, 201):
        val = metrics[pid]["value"]
        if isinstance(val, (int, float)):
            c.drawString(28, y, f"{pid}: {val}")
            y -= 16; count += 1
        if count >= 10: break
    c.setFont("Helvetica", 10)
    c.drawString(20, 30, "© FF Tech • Premium 5‑page PDF")
    c.showPage()

    c.save()
    return buf.getvalue()
