
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib import colors
from reportlab.lib.units import mm
from io import BytesIO

TITLE_COLOR = colors.HexColor('#00ADB5')
TEXT_COLOR = colors.HexColor('#111')


def _draw_header(c, title):
    c.setFillColor(TITLE_COLOR)
    c.setFont('Helvetica-Bold', 18)
    c.drawString(30, 800, title)
    c.setFillColor(TEXT_COLOR)


def _draw_kv(c, x, y, k, v):
    c.setFont('Helvetica-Bold', 11)
    c.drawString(x, y, str(k))
    c.setFont('Helvetica', 11)
    c.drawString(x+180, y, str(v))


def build_pdf_report(audit, categories: dict, strengths: list, weaknesses: list, fixes: list) -> bytes:
    buf = BytesIO()
    c = canvas.Canvas(buf, pagesize=A4)

    # Page 1: Cover
    _draw_header(c, 'FF Tech AI • Website Audit Report')
    _draw_kv(c, 30, 760, 'URL:', getattr(audit, 'url', ''))
    _draw_kv(c, 30, 740, 'Score:', getattr(audit, 'score', ''))
    _draw_kv(c, 30, 720, 'Grade:', getattr(audit, 'grade', ''))
    c.setFont('Helvetica', 10)
    c.drawString(30, 700, 'This is a certified, executive-ready 5-page report.')
    c.showPage()

    # Page 2: Category scores
    _draw_header(c, 'Category Score Breakdown')
    y = 760
    for k in ['security','performance','seo','mobile','content']:
        _draw_kv(c, 30, y, k.title(), categories.get(k, 'N/A'))
        y -= 22
    c.showPage()

    # Page 3: Strengths & Weaknesses
    _draw_header(c, 'Strengths & Weak Areas')
    c.setFont('Helvetica-Bold', 12); c.drawString(30, 760, 'Strengths')
    c.setFont('Helvetica', 11)
    y = 740
    for s in strengths[:12]:
        c.drawString(30, y, f"• {s}"); y -= 18
    c.setFont('Helvetica-Bold', 12); c.drawString(30, y-10, 'Weak Areas')
    y -= 30
    c.setFont('Helvetica', 11)
    for w in weaknesses[:12]:
        c.drawString(30, y, f"• {w}"); y -= 18
    c.showPage()

    # Page 4: Priority Fixes
    _draw_header(c, 'Priority Fixes')
    c.setFont('Helvetica', 11)
    y = 760
    for f in fixes[:18]:
        c.drawString(30, y, f"• {f}"); y -= 18
    c.showPage()

    # Page 5: Executive Notes
    _draw_header(c, 'Executive Notes')
    c.setFont('Helvetica', 11)
    c.drawString(30, 760, 'This report is automatically generated by FF Tech AI.')
    c.drawString(30, 740, 'For continuous monitoring, enable daily/weekly/monthly schedules.')
    c.showPage()

    c.save()
    data = buf.getvalue(); buf.close()
    return data
