
(()=>{
  const API={
    sendLink:async(email)=>fetch('/auth/send-link',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email})}).then(r=>r.json()),
    verify:async(token)=>fetch('/auth/verify',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token})}).then(r=>r.json()),
    audit:async(jwt,url)=>fetch('/audit',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+jwt},body:JSON.stringify({url})}).then(r=>r.json()),
    adminAudits:async(jwt)=>fetch('/admin/audits',{headers:{'Authorization':'Bearer '+jwt}}).then(r=>r.json())
  };
  const el=id=>document.getElementById(id);
  const navLinks=document.querySelectorAll('.nav a');const panels=document.querySelectorAll('.panel');
  navLinks.forEach(a=>a.addEventListener('click',e=>{e.preventDefault();const t=a.getAttribute('href').replace('#','');navLinks.forEach(n=>n.classList.remove('active'));a.classList.add('active');panels.forEach(p=>p.classList.add('hidden'));document.getElementById(t).classList.remove('hidden');if(t==='admin')loadAdmin();if(t==='history')loadHistory();}));
  el('btn-send-link').addEventListener('click',async()=>{const email=el('email').value.trim();if(!email)return alert('Enter email');const res=await API.sendLink(email);if(res.token){el('token').value=res.token;alert('Token generated (demo). In production, it would be emailed.');}else alert('Failed to generate token');});
  el('btn-verify').addEventListener('click',async()=>{const token=el('token').value.trim();if(!token)return alert('Paste the token');const res=await API.verify(token);if(res.access_token){localStorage.setItem('jwt',res.access_token);alert('Verified! JWT stored.');}else alert('Invalid/expired token');});
  el('btn-audit').addEventListener('click',async()=>{const url=el('url').value.trim();const jwt=localStorage.getItem('jwt');if(!jwt)return alert('Verify to get JWT first.');if(!url)return alert('Enter a URL');const res=await API.audit(jwt,url);if(res.audit_id){renderAudit(res.audit_id,res.result);}else alert('Audit failed');});
  async function renderAudit(audit_id,result){const grid=el('category-grid');grid.innerHTML='';const gradeEl=el('grade');gradeEl.textContent=`Audit ID: ${audit_id} · Grade: ${result.grade} · Overall: ${result.overall_score}%`;
    const map=[['executive','Executive Summary & Grading'],['health','Overall Site Health'],['crawl','Crawlability & Indexation'],['seo','On-Page SEO'],['performance','Performance & Technical'],['mobile_security_international','Mobile, Security & International'],['competitor','Competitor Analysis'],['broken_links','Broken Links Intelligence'],['opportunities','Opportunities, Growth & ROI']];
    const dataForChart=[];map.forEach(([key,label])=>{const score=(result.categories[key]&&typeof result.categories[key].score!=='undefined')?result.categories[key].score:null;dataForChart.push(score||0);const card=document.createElement('div');card.className='card';card.innerHTML=`<h3>${label}</h3><div class="kv"><span>Score</span><strong>${score!==null?score+'%':'N/A'}</strong></div><div class="progress"><span style="width:${score||0}%"></span></div>`;grid.appendChild(card);});
    renderCharts(map.map(m=>m[1]),dataForChart);
    const details=el('details');details.innerHTML='<h3>Executive Summary</h3><pre class="item"></pre>';details.querySelector('pre').textContent=(result.metrics&&result.metrics.A&&result.metrics.A["Executive Summary (Auto-Generated)"])||'';
    const hist=JSON.parse(localStorage.getItem('history')||'[]');hist.unshift({id:audit_id,grade:result.grade,overall:result.overall_score,at:new Date().toISOString()});localStorage.setItem('history',JSON.stringify(hist.slice(0,20)));
  }
  function renderCharts(labels,values){const ctx1=document.getElementById('categoryChart');const ctx2=document.getElementById('trendChart');new Chart(ctx1,{type:'radar',data:{labels,datasets:[{label:'Category Scores',data:values,borderColor:'#45a0ff',backgroundColor:'rgba(69,160,255,0.2)'}]},options:{scales:{r:{suggestedMin:0,suggestedMax:100}}}});new Chart(ctx2,{type:'line',data:{labels:labels.slice(0,6),datasets:[{label:'Recent Trend (stub)',data:values.slice(0,6).map(v=>v?Math.max(0,Math.min(100,v+(Math.random()*10-5))):0),borderColor:'#6be795'}]},options:{plugins:{legend:{display:false}},scales:{y:{min:0,max:100}}});}
  async function loadAdmin(){const jwt=localStorage.getItem('jwt');if(!jwt)return;const rows=await API.adminAudits(jwt);const list=el('admin-list');list.innerHTML='';if(Array.isArray(rows)){rows.forEach(r=>{const div=document.createElement('div');div.className='item';div.innerHTML=`<strong>${r.site}</strong> · Grade ${r.grade} · ${r.overall_score}% · <a href="/report/${r.audit_id}" target="_blank">PDF</a>`;list.appendChild(div);});}}
  function loadHistory(){const hist=JSON.parse(localStorage.getItem('history')||'[]');const list=el('history-list');list.innerHTML='';hist.forEach(h=>{const div=document.createElement('div');div.className='item';div.innerHTML=`${h.at} · <strong>${h.id}</strong> · Grade ${h.grade} · ${h.overall}%`;list.appendChild(div);});}
})();
