
# Registry of IDs 1..200 mapped to canonical metric keys
# (Full list aligned to your framework)
EXECUTIVE = {1:'overall_site_health_score',2:'website_grade',3:'executive_summary',4:'strengths',5:'weaknesses',6:'priority_fixes',7:'severity_indicators',8:'category_breakdown',9:'presentation_standard',10:'export_readiness'}
OVERALL   = {11:'site_health_score',12:'total_errors',13:'total_warnings',14:'total_notices',15:'total_crawled_pages',16:'total_indexed_pages',17:'issues_trend',18:'crawl_budget_efficiency',19:'orphan_pages_pct',20:'audit_completion_status'}
CRAWLABILITY = {21:'http_2xx',22:'http_3xx',23:'http_4xx',24:'http_5xx',25:'redirect_chains',26:'redirect_loops',27:'broken_internal_links',28:'broken_external_links',29:'robots_blocked',30:'meta_robots_blocked',31:'non_canonical_pages',32:'missing_canonical',33:'incorrect_canonical',34:'sitemap_missing_pages',35:'sitemap_not_crawled',36:'hreflang_errors',37:'hreflang_conflicts',38:'pagination_issues',39:'crawl_depth_distribution',40:'duplicate_param_urls'}
ONPAGE = {41:'missing_title',42:'duplicate_title',43:'title_too_long',44:'title_too_short',45:'missing_meta_desc',46:'duplicate_meta_desc',47:'meta_too_long',48:'meta_too_short',49:'missing_h1',50:'multiple_h1',51:'duplicate_headings',52:'thin_content',53:'duplicate_content',54:'low_text_html_ratio',55:'missing_img_alt',56:'duplicate_img_alt',57:'large_uncompressed_images',58:'pages_without_indexed_content',59:'missing_structured_data',60:'structured_data_errors',61:'rich_snippet_warnings',62:'missing_og_tags',63:'long_urls',64:'uppercase_urls',65:'non_seo_friendly_urls',66:'too_many_internal_links',67:'pages_without_incoming_links',68:'orphan_pages',69:'broken_anchor_links',70:'redirected_internal_links',71:'nofollow_internal_links',72:'link_depth_issues',73:'external_links_count',74:'broken_external_links_onpage',75:'anchor_text_issues'}
PERF = {76:'lcp',77:'fcp',78:'cls',79:'total_blocking_time',80:'first_input_delay',81:'speed_index',82:'tti',83:'dom_content_loaded',84:'total_page_size',85:'requests_per_page',86:'unminified_css',87:'unminified_js',88:'render_blocking',89:'excessive_dom',90:'third_party_script_load',91:'server_response_time',92:'image_optimization',93:'lazy_loading_issues',94:'browser_caching_issues',95:'missing_compression',96:'resource_load_errors'}
MSI = {97:'mobile_friendly',98:'viewport_meta',99:'small_font_issues',100:'tap_target_issues',101:'mobile_cwv',102:'mobile_layout_issues',103:'intrusive_interstitials',104:'mobile_nav_issues',105:'https_implementation',106:'ssl_validity',107:'expired_ssl',108:'mixed_content',109:'insecure_resources',110:'missing_security_headers',111:'open_directory_listing',112:'login_without_https',113:'missing_hreflang',114:'incorrect_language_codes',115:'hreflang_conflicts_intl',116:'region_target_issues',117:'multi_domain_seo_issues',118:'domain_authority',119:'referring_domains',120:'total_backlinks',121:'toxic_backlinks',122:'nofollow_backlinks',123:'anchor_distribution',124:'referring_ips',125:'lost_new_backlinks',126:'js_rendering_issues',127:'css_blocking',128:'crawl_budget_waste',129:'amp_issues',130:'pwa_issues',131:'canonical_conflicts',132:'subdomain_duplication',133:'pagination_conflicts',134:'dynamic_url_issues',135:'lazy_load_conflicts',136:'sitemap_presence',137:'noindex_issues',138:'structured_data_consistency',139:'redirect_correctness',140:'broken_rich_media',141:'social_metadata_presence',142:'error_trend',143:'health_trend',144:'crawl_trend',145:'index_trend',146:'cwv_trend',147:'backlink_trend',148:'keyword_trend',149:'historical_comparison',150:'overall_stability_index'}
COMP = {151:'competitor_health_score',152:'competitor_performance_comparison',153:'competitor_cwv_comparison',154:'competitor_seo_issues_comparison',155:'competitor_broken_links',156:'competitor_authority_score',157:'competitor_backlink_growth',158:'competitor_keyword_visibility',159:'competitor_rank_distribution',160:'competitor_content_volume',161:'competitor_speed_comparison',162:'competitor_mobile_score',163:'competitor_security_score',164:'competitive_gap_score',165:'competitive_opportunity_heatmap',166:'competitive_risk_heatmap',167:'overall_competitive_rank'}
BROKEN = {168:'total_broken_links',169:'internal_broken_links',170:'external_broken_links',171:'broken_links_trend',172:'broken_pages_by_impact',173:'status_code_distribution',174:'page_type_distribution',175:'fix_priority_score',176:'seo_loss_impact',177:'affected_pages_count',178:'broken_media_links',179:'resolution_progress',180:'risk_severity_index'}
OPP = {181:'high_impact_opportunities',182:'quick_wins_score',183:'long_term_fixes',184:'traffic_growth_forecast',185:'ranking_growth_forecast',186:'conversion_impact_score',187:'content_expansion_opportunities',188:'internal_linking_opportunities',189:'speed_improvement_potential',190:'mobile_improvement_potential',191:'security_improvement_potential',192:'structured_data_opportunities',193:'crawl_optimization_potential',194:'backlink_opportunity_score',195:'competitive_gap_roi',196:'fix_roadmap_timeline',197:'time_to_fix_estimate',198:'cost_to_fix_estimate',199:'roi_forecast',200:'overall_growth_readiness'}
