from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.pdfgen import canvas
from reportlab.lib import colors
import math

# --- Utilities ---

def bar(c, x, y, w, h, color):
    c.setFillColor(color)
    c.rect(x, y, w, h, fill=1, stroke=0)

def draw_header(c, brand_name):
    """Draws the professional blue header bar on every page."""
    c.setFillColor(colors.HexColor('#0057D9'))
    c.rect(0*mm, 285*mm, 210*mm, 12*mm, fill=1, stroke=0)
    c.setFillColor(colors.white)
    c.setFont("Helvetica-Bold", 14)
    c.drawString(12*mm, 289*mm, f"{brand_name} · Certified Website Audit")
    c.setFillColor(colors.black)

def draw_footer(c):
    """Draws the grey footer with legal/brand info on every page."""
    c.setFont("Helvetica", 9)
    c.setFillColor(colors.HexColor('#7f8c8d'))
    c.drawRightString(198*mm, 10*mm, "Generated by FF Tech · Confidential Analysis")
    c.setFillColor(colors.black)

# --- Page Layouts ---

def page_cover(c, brand_name, url):
    draw_header(c, brand_name)
    c.setFont("Helvetica-Bold", 32)
    c.setFillColor(colors.HexColor('#2C3E50'))
    c.drawString(12*mm, 240*mm, "Website Audit Report")
    
    c.setFont("Helvetica", 16)
    c.setFillColor(colors.black)
    c.drawString(12*mm, 228*mm, f"Target Domain: {url}")
    
    # Hero Box
    c.setFillColor(colors.HexColor('#F8F9FA'))
    c.rect(12*mm, 100*mm, 186*mm, 100*mm, fill=1, stroke=1)
    
    c.setFillColor(colors.HexColor('#0057D9'))
    c.setFont("Helvetica-Bold", 54)
    c.drawString(30*mm, 150*mm, "FF • TECH")
    
    c.setFont("Helvetica", 10)
    c.setFillColor(colors.HexColor('#7f8c8d'))
    c.drawString(12*mm, 90*mm, f"Report generated on: {colors.black}") # Date logic handled in main
    draw_footer(c)

def page_summary(c, brand_name, grade, health_score, exec_summary):
    draw_header(c, brand_name)
    c.setFont("Helvetica-Bold", 20)
    c.drawString(12*mm, 260*mm, "Executive Summary")
    
    # Grade Badge
    c.setFillColor(colors.HexColor('#0057D9'))
    c.rect(12*mm, 242*mm, 40*mm, 12*mm, fill=1, stroke=0)
    c.setFillColor(colors.white)
    c.setFont("Helvetica-Bold", 12)
    c.drawCentredString(32*mm, 245*mm, f"GRADE: {grade}")
    
    c.setFillColor(colors.black)
    t = c.beginText(12*mm, 220*mm)
    t.setFont("Helvetica", 11)
    t.setLeading(16)
    
    # Wrap text logic
    summary_text = exec_summary or "No summary provided."
    for line in summary_text.split('. '):
        if line:
            t.textLine(f"• {line.strip()}.")
    c.drawText(t)

    # Health Score Circular Indicator
    c.setFillColor(colors.HexColor('#ECF0F1'))
    c.circle(165*mm, 190*mm, 28*mm, fill=1, stroke=0)
    c.setFillColor(colors.HexColor('#1ABC9C'))
    c.circle(165*mm, 190*mm, 24*mm, fill=1, stroke=0)
    c.setFillColor(colors.white)
    c.setFont("Helvetica-Bold", 22)
    c.drawCentredString(165*mm, 187*mm, str(health_score))
    
    draw_footer(c)

def page_bars(c, brand_name, category_scores):
    draw_header(c, brand_name)
    c.setFont("Helvetica-Bold", 18)
    c.drawString(12*mm, 260*mm, "Metric Pillar Analysis")
    
    base_y = 230*mm
    maxw = 150*mm
    palette = [colors.HexColor('#0057D9'), colors.HexColor('#1ABC9C'), colors.HexColor('#F39C12'), colors.HexColor('#8E44AD'), colors.HexColor('#E74C3C')]
    
    for i, item in enumerate(category_scores):
        name = item['name']
        score = int(item['score'])
        y_pos = base_y - (i * 22*mm)
        
        # Label
        c.setFillColor(colors.black)
        c.setFont("Helvetica-Bold", 11)
        c.drawString(12*mm, y_pos + 8*mm, f"{name}")
        
        # Background track
        c.setFillColor(colors.HexColor('#F1F2F6'))
        c.rect(12*mm, y_pos, maxw, 6*mm, fill=1, stroke=0)
        
        # Score bar
        bar(c, 12*mm, y_pos, maxw * (score/100.0), 6*mm, palette[i % len(palette)])
        
        # Percentage text
        c.setFont("Helvetica-Bold", 11)
        c.drawString(170*mm, y_pos + 1*mm, f"{score}%")

    draw_footer(c)

def page_competitor_analysis(c, brand_name, category_scores):
    """NEW: Injects Competitor Comparison into the PDF."""
    draw_header(c, brand_name)
    c.setFont("Helvetica-Bold", 18)
    c.drawString(12*mm, 260*mm, "Industry Benchmark Comparison")
    
    # Table Header
    c.setFillColor(colors.HexColor('#2C3E50'))
    c.rect(12*mm, 240*mm, 186*mm, 10*mm, fill=1, stroke=0)
    c.setFillColor(colors.white)
    c.setFont("Helvetica-Bold", 10)
    c.drawString(15*mm, 243*mm, "Category")
    c.drawString(80*mm, 243*mm, "Your Score")
    c.drawString(120*mm, 243*mm, "Industry Avg")
    c.drawString(160*mm, 243*mm, "Gap")

    y = 230*mm
    baseline_val = 82 # Internal industry standard
    
    for item in category_scores:
        score = int(item['score'])
        gap = score - baseline_val
        
        c.setFillColor(colors.black)
        c.setFont("Helvetica", 10)
        c.drawString(15*mm, y, item['name'])
        c.drawString(85*mm, y, f"{score}%")
        c.drawString(125*mm, y, f"{baseline_val}%")
        
        if gap >= 0:
            c.setFillColor(colors.darkgreen)
            c.drawString(165*mm, y, f"+{gap}")
        else:
            c.setFillColor(colors.red)
            c.drawString(165*mm, y, f"{gap}")
            
        y -= 12*mm
    
    draw_footer(c)

def render_pdf(path, brand_name, url, grade, health_score, category_scores, exec_summary):
    """Orchestrates the creation of the 5-page audit document."""
    cs = category_scores or []
    c = canvas.Canvas(path, pagesize=A4)
    
    page_cover(c, brand_name, url)
    c.showPage()
    
    page_summary(c, brand_name, grade, health_score, exec_summary)
    c.showPage()
    
    page_bars(c, brand_name, cs)
    c.showPage()
    
    page_competitor_analysis(c, brand_name, cs)
    c.showPage()
    
    # Page Radar / Distribution (Simplified for PDF stability)
    draw_header(c, brand_name)
    c.setFont("Helvetica-Bold", 18)
    c.drawString(12*mm, 260*mm, "Final Recommendations")
    
    recos = [
        "Enable GZIP/Brotli compression for text assets.",
        "Implement HSTS and upgrade to TLS 1.3.",
        "Fix cumulative layout shift (CLS) on mobile viewport.",
        "Add ARIA labels to non-text interactive elements.",
        "Optimize LCP (Largest Contentful Paint) by preloading hero images."
    ]
    
    ry = 230*mm
    for r in recos:
        c.setFillColor(colors.HexColor('#0057D9'))
        c.circle(15*mm, ry+1*mm, 1*mm, fill=1, stroke=0)
        c.setFillColor(colors.black)
        c.setFont("Helvetica", 11)
        c.drawString(20*mm, ry, r)
        ry -= 15*mm

    draw_footer(c)
    c.showPage()
    
    c.save()
