from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.pdfgen import canvas
from reportlab.lib import colors

def draw_header(c, brand_name):
    c.setFillColor(colors.HexColor('#0057D9'))
    c.rect(0*mm, 285*mm, 210*mm, 12*mm, fill=1, stroke=0)
    c.setFillColor(colors.white)
    c.setFont('Helvetica-Bold', 14)
    c.drawString(12*mm, 289*mm, f"{brand_name} · Certified Website Audit")
    c.setFillColor(colors.black)

def draw_footer(c):
    c.setFont('Helvetica', 9)
    c.setFillColor(colors.HexColor('#7f8c8d'))
    c.drawRightString(198*mm, 10*mm, 'Generated by FF Tech · Confidential')
    c.setFillColor(colors.black)

def draw_cover(c, brand_name, url):
    draw_header(c, brand_name)
    c.setFont('Helvetica-Bold', 24)
    c.drawString(12*mm, 240*mm, 'Certified Audit Report')
    c.setFont('Helvetica', 14)
    c.drawString(12*mm, 228*mm, f'Domain: {url}')
    c.setFont('Helvetica', 12)
    c.drawString(12*mm, 216*mm, 'Prepared by FF Tech')
    c.setFillColor(colors.HexColor('#ecf0f1'))
    c.rect(12*mm, 120*mm, 186*mm, 80*mm, fill=1, stroke=0)
    c.setFillColor(colors.HexColor('#0057D9'))
    c.setFont('Helvetica-Bold', 48)
    c.drawString(20*mm, 160*mm, 'FF • TECH')
    c.setFillColor(colors.black)
    draw_footer(c)

def draw_summary(c, brand_name, grade, health_score, exec_summary):
    draw_header(c, brand_name)
    c.setFont('Helvetica-Bold', 16)
    c.drawString(12*mm, 260*mm, 'Executive Summary')
    c.setFont('Helvetica', 12)
    c.drawString(12*mm, 248*mm, f'Grade: {grade} · Health Score: {health_score}/100')
    text = c.beginText(12*mm, 238*mm)
    text.setFont('Helvetica', 11)
    text.setLeading(14)
    for line in (exec_summary or '').split('. '):
        text.textLine(line.strip())
    c.drawText(text)
    c.setFillColor(colors.HexColor('#ecf0f1'))
    c.circle(160*mm, 190*mm, 25*mm, fill=1, stroke=0)
    c.setFillColor(colors.HexColor('#1abc9c'))
    c.circle(160*mm, 190*mm, 20*mm, fill=1, stroke=0)
    c.setFillColor(colors.white)
    c.setFont('Helvetica-Bold', 18)
    c.drawCentredString(160*mm, 190*mm, str(health_score))
    c.setFillColor(colors.black)
    draw_footer(c)

def draw_categories(c, brand_name, category_scores):
    draw_header(c, brand_name)
    c.setFont('Helvetica-Bold', 16)
    c.drawString(12*mm, 260*mm, 'Category Scores')
    baseline_y = 240*mm
    bar_height = 8*mm
    x0 = 12*mm
    max_w = 180*mm
    c.setFont('Helvetica', 11)
    for i, item in enumerate(category_scores):
        name = item.get('name')
        score = int(item.get('score', 0))
        y = baseline_y - i*15*mm
        c.setFillColor(colors.HexColor('#3498db'))
        c.rect(x0, y, max_w * (score/100.0), bar_height, fill=1, stroke=0)
        c.setFillColor(colors.black)
        c.drawString(x0, y + 10, f"{name}: {score}%")
    draw_footer(c)

def draw_radar_like(c, brand_name, category_scores):
    draw_header(c, brand_name)
    c.setFont('Helvetica-Bold', 16)
    c.drawString(12*mm, 260*mm, 'Distribution View')
    cx, cy = 105*mm, 170*mm
    radius = 60*mm
    c.setStrokeColor(colors.HexColor('#bdc3c7'))
    for r in [radius*0.4, radius*0.7, radius]:
        c.circle(cx, cy, r, stroke=1, fill=0)
    import math
    n = max(1, len(category_scores))
    for i, item in enumerate(category_scores):
        angle = (2*math.pi * i)/n
        score = int(item.get('score', 0))/100.0
        x = cx + radius*score*math.cos(angle)
        y = cy + radius*score*math.sin(angle)
        c.setFillColor(colors.HexColor('#e74c3c'))
        c.circle(x, y, 3*mm, fill=1, stroke=0)
        c.setFillColor(colors.black)
        c.setFont('Helvetica', 10)
        c.drawString(cx + (radius+5*mm)*math.cos(angle), cy + (radius+5*mm)*math.sin(angle), item.get('name'))
    draw_footer(c)

def draw_recommendations(c, brand_name, exec_summary):
    draw_header(c, brand_name)
    c.setFont('Helvetica-Bold', 16)
    c.drawString(12*mm, 260*mm, 'Recommendations')
    c.setFont('Helvetica', 11)
    lines = [
        '• Optimize images (modern formats, compression)',
        '• Remove unused JS/CSS, enable HTTP/2',
        '• Improve server TTFB (cache, CDN)',
        '• Add meta tags and structured data',
        '• Ensure WCAG contrast and alt texts',
    ]
    y = 240*mm
    for ln in lines:
        c.drawString(12*mm, y, ln)
        y -= 12*mm
    c.setFillColor(colors.HexColor('#2c3e50'))
    c.rect(12*mm, 60*mm, 186*mm, 40*mm, fill=1, stroke=0)
    c.setFillColor(colors.white)
    c.setFont('Helvetica-Bold', 12)
    c.drawString(16*mm, 85*mm, 'This report is auto-generated. For a deep-dive, contact FF Tech.')
    c.setFillColor(colors.black)
    draw_footer(c)

def render_pdf(path, brand_name, url, grade, health_score, category_scores, exec_summary):
    c = canvas.Canvas(path, pagesize=A4)
    draw_cover(c, brand_name, url)
    c.showPage()
    draw_summary(c, brand_name, grade, health_score, exec_summary)
    c.showPage()
    draw_categories(c, brand_name, category_scores or [])
    c.showPage()
    draw_radar_like(c, brand_name, category_scores or [])
    c.showPage()
    draw_recommendations(c, brand_name, exec_summary)
    c.showPage()
    c.save()
