from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.pdfgen import canvas
from reportlab.lib import colors

# Simple chart utilities

def bar(c, x, y, w, h, color):
    c.setFillColor(color); c.rect(x, y, w, h, fill=1, stroke=0)


def draw_header(c, brand_name):
    c.setFillColor(colors.HexColor('#0057D9'))
    c.rect(0*mm, 285*mm, 210*mm, 12*mm, fill=1, stroke=0)
    c.setFillColor(colors.white)
    c.setFont("Helvetica-Bold", 14)
    c.drawString(12*mm, 289*mm, f"{brand_name} · Certified Website Audit")
    c.setFillColor(colors.black)


def draw_footer(c):
    c.setFont("Helvetica", 9)
    c.setFillColor(colors.HexColor('#7f8c8d'))
    c.drawRightString(198*mm, 10*mm, "Generated by FF Tech · Confidential")
    c.setFillColor(colors.black)


def page_cover(c, brand_name, url):
    draw_header(c, brand_name)
    c.setFont("Helvetica-Bold", 26); c.setFillColor(colors.HexColor('#2C3E50'))
    c.drawString(12*mm, 240*mm, "Website Audit Report")
    c.setFont("Helvetica", 14); c.setFillColor(colors.black)
    c.drawString(12*mm, 228*mm, f"Domain: {url}")
    c.setFillColor(colors.HexColor('#ECF0F1'))
    c.rect(12*mm, 120*mm, 186*mm, 80*mm, fill=1, stroke=0)
    c.setFillColor(colors.HexColor('#0057D9'))
    c.setFont("Helvetica-Bold", 48)
    c.drawString(20*mm, 160*mm, "FF • TECH")
    c.setFillColor(colors.black)
    draw_footer(c)


def page_summary(c, brand_name, grade, health_score, exec_summary):
    draw_header(c, brand_name)
    c.setFont("Helvetica-Bold", 18)
    c.drawString(12*mm, 260*mm, "Executive Summary")
    c.setFont("Helvetica", 12)
    c.drawString(12*mm, 248*mm, f"Grade: {grade} · Health Score: {health_score}/100")
    t = c.beginText(12*mm, 236*mm); t.setFont("Helvetica", 11); t.setLeading(14)
    for line in (exec_summary or "").split('. '):
        t.textLine(line.strip())
    c.drawText(t)
    # Donut-like indicator
    c.setFillColor(colors.HexColor('#ECF0F1'))
    c.circle(165*mm, 190*mm, 28*mm, fill=1, stroke=0)
    c.setFillColor(colors.HexColor('#1ABC9C'))
    c.circle(165*mm, 190*mm, 24*mm, fill=1, stroke=0)
    c.setFillColor(colors.white); c.setFont("Helvetica-Bold", 20)
    c.drawCentredString(165*mm, 190*mm, str(health_score))
    c.setFillColor(colors.black)
    draw_footer(c)


def page_bars(c, brand_name, category_scores):
    draw_header(c, brand_name)
    c.setFont("Helvetica-Bold", 18); c.drawString(12*mm, 260*mm, "Category Scores")
    base_y = 240*mm; h = 10*mm; x = 12*mm; maxw = 180*mm
    palette = [colors.HexColor('#0057D9'), colors.HexColor('#1ABC9C'), colors.HexColor('#F39C12'), colors.HexColor('#8E44AD'), colors.HexColor('#E74C3C')]
    for i, item in enumerate(category_scores):
        name = item['name']; score = int(item['score']); y = base_y - i*18*mm
        bar(c, x, y, maxw * (score/100.0), h, palette[i % len(palette)])
        c.setFont("Helvetica", 11); c.setFillColor(colors.black)
        c.drawString(x, y + h + 3, f"{name}: {score}%")
    draw_footer(c)


def page_radar(c, brand_name, category_scores):
    draw_header(c, brand_name)
    c.setFont("Helvetica-Bold", 18); c.drawString(12*mm, 260*mm, "Distribution View")
    # Polar-like points
    cx, cy, r = 105*mm, 170*mm, 60*mm
    c.setStrokeColor(colors.HexColor('#BDC3C7'))
    for rr in [r*0.4, r*0.7, r]: c.circle(cx, cy, rr, stroke=1, fill=0)
    import math
    palette = [colors.HexColor('#0057D9'), colors.HexColor('#1ABC9C'), colors.HexColor('#F39C12'), colors.HexColor('#8E44AD'), colors.HexColor('#E74C3C')]
    for i, item in enumerate(category_scores):
        angle = (2*math.pi * i) / max(1, len(category_scores))
        score = int(item['score'])/100.0
        x = cx + r*score*math.cos(angle); y = cy + r*score*math.sin(angle)
        c.setFillColor(palette[i % len(palette)])
        c.circle(x, y, 4*mm, fill=1, stroke=0)
        c.setFillColor(colors.black); c.setFont("Helvetica", 10)
        c.drawString(cx + (r+5*mm)*math.cos(angle), cy + (r+5*mm)*math.sin(angle), item['name'])
    draw_footer(c)


def page_recos(c, brand_name, exec_summary):
    draw_header(c, brand_name)
    c.setFont("Helvetica-Bold", 18); c.drawString(12*mm, 260*mm, "Recommendations")
    c.setFont("Helvetica", 12)
    bullets = [
        "Optimize images and enable caching",
        "Minify and defer unused JS/CSS",
        "Add meta description and canonical",
        "Ensure alt text and language attributes",
        "Set CSP, XFO, and HSTS security headers"
    ]
    y = 240*mm
    for b in bullets:
        c.drawString(12*mm, y, f"• {b}"); y -= 14*mm
    c.setFillColor(colors.HexColor('#ECF0F1'))
    c.rect(12*mm, 70*mm, 186*mm, 60*mm, fill=1, stroke=0)
    c.setFillColor(colors.HexColor('#2C3E50')); c.setFont("Helvetica-Bold", 12)
    c.drawString(16*mm, 120*mm, "Need deeper analysis? Contact FF Tech.")
    c.setFillColor(colors.black)
    draw_footer(c)


def render_pdf(path, brand_name, url, grade, health_score, category_scores, exec_summary):
    cs = category_scores or []
    c = canvas.Canvas(path, pagesize=A4)
    page_cover(c, brand_name, url); c.showPage()
    page_summary(c, brand_name, grade, health_score, exec_summary); c.showPage()
    page_bars(c, brand_name, cs); c.showPage()
    page_radar(c, brand_name, cs); c.showPage()
    page_recos(c, brand_name, exec_summary); c.showPage()
    c.save()
